### ISSUE TITLE
Getting warnings when activating Stripe Version 1.1.2.rc.001 with EE Version 4.9.56.rc.017

### ISSUE THREAD

**Issue by mrjonwilson** [eventespresso/eea-stripe-gateway#1]
`Cannot send session cache limiter - headers already sent (output started at /home/outdoo38/public_html/faccarthage/wp-content/plugins/eea-stripe-gateway-master/payment_methods/Stripe_Onsite/EE_PMT_Stripe_Onsite.pm.php:1) in /home/outdoo38/public_html/faccarthage/wp-content/plugins/event-espresso-core-master/core/EE_Session.core.php on line 527`

`Warning: Cannot modify header information - headers already sent by (output started at /home/outdoo38/public_html/faccarthage/wp-content/plugins/eea-stripe-gateway-master/payment_methods/Stripe_Onsite/EE_PMT_Stripe_Onsite.pm.php:1) in /home/outdoo38/public_html/faccarthage/wp-admin/includes/misc.php on line 1114`

**Comment by mnelson4** [comment]
Thanks for the report Jonathan, it seems we somehow added a blank line at the start of the file mentioned in the warning! We’ll get this fixed ASAP

**Comment by mrjonwilson** [comment]
My pleasure! Thanks for the quick response, Mike!

**Comment by mnelson4** [comment]
A fix has been pushed to this master branch. We'll be releasing the fix on PUE in the next day or two.

Take care Jonathan!

**Comment by mrjonwilson** [comment]
Thanks, Mike!
